### ISSUE TITLE
Constructors aren't bound?

### ISSUE THREAD

**Issue by LiamGoodacre** [natefaubion/adt.js#10]
Given the following setup:

``` js
var adt = require('adt')

var Option = adt.data()
var None = Option.type('None')
var Some = Option.type('Some', { value: adt.any })

Option.apply = function (ctx, args) {
  if (args.length !== 1)
    throw new Error('Option expects exactly 1 argument.')
  var value = args[0]
  return (value == null) ? None : Some(value)
}
```

Observe the following behaviour:

``` js
> Some(Some).value(12)
undefined

> Some(Some.bind(Some)).value(12)
{ value: 12 }

> Some(Some.bind()).value(12)
{ value: 12 }

> Option(Option).value(12)
Error: Bad invocation
    at null.<anonymous> (.../node_modules/adt/adt.js:52:13)
    at repl:1:16
    at REPLServer.defaultEval (repl.js:129:27)
    at REPLServer.b [as eval] (domain.js:251:18)
    at Interface.<anonymous> (repl.js:277:12)
    at Interface.EventEmitter.emit (events.js:103:17)
    at Interface._onLine (readline.js:194:10)
    at Interface._line (readline.js:523:8)
    at Interface._ttyWrite (readline.js:798:14)
    at ReadStream.onkeypress (readline.js:98:10)

> Option(Option.bind(Option)).value(12)
{ value: 12 }

>  Option(Option.bind()).value(12)
{ value: 12 }
```

Not fully sure what's going on, but looks as if the data constructors aren't being bound when they should be?

Any thoughts on this?

Thanks.

**Comment by natefaubion** [comment]
Oh my. A user! ;)

This is actually a really interesting edge case with the `!(this instance of Foo)` newless constructor pattern. So basically, you have something like this:

``` js
function Foo() {
  if (!(this instanceof Foo)) {
    return new Foo();
  }
}
```

Under normal invocation of `Foo`, if you leave off the `new`, `this` will refer to the global. But what happens when `Foo` is itself a property of an instance of `Foo`? You get the edge case you've just highlighted.

``` js
var foo = new Foo();
foo.Foo = Foo;

foo.Foo() // oh no! `this` is now an instance of Foo even though I called it without `new`!
```

Not much to do about it I'm afraid.

**Comment by michaelficarra** [comment]
It gets worse! Your example could be defeated with a test like `{}.hasOwnProperty.call(this, 'Foo')`, since the new instance would not have any own-properties. Or more generically, the test could be `Object.getOwnPropertyNames(this).length`. But if you stuck the property on the prototype instead (`Foo.prototype.Foo = Foo` instead of `foo.Foo = Foo`), I can't think of a test that could distinguish a use of `new` from the method call. Very cool, thanks for pointing this out.

**Comment by LiamGoodacre** [comment]
All we need to do is bind the constructors before releasing them -  when the bound constructor is called, `this` will always be undefined; causing the internal `instanceof` to fail - thereby creating a new instance.  As follows:

``` js
//  Basic constructor
function Foo1(a) {
  if (!(this instanceof Foo1))
    return new Foo1(a)
  this.a = a
};

//  Bound version
var Foo2 = Foo1.bind();

//  Some test values
var v1 = Foo1(1)
var v2 = Foo2(1)
var e1 = Foo1(Foo1).a(1)
var e2 = Foo2(Foo2).a(1)

//  Value checks
assert(v1.a === 1)
assert(v2.a === 1)
assert(e1 === undefined)
assert(e2.a === 1)

//  Note that values of either are instances of both constructors
assert(v1 instanceof Foo1)
assert(v1 instanceof Foo2)
assert(v2 instanceof Foo1)
assert(v2 instanceof Foo2)
assert(e2 instanceof Foo1)
assert(e2 instanceof Foo2)

//  Rebinding
var b1 = Foo1.bind(Foo1(1))(2)
var b2 = Foo2.bind(Foo1(1))(2)
assert(b1 === undefined)
assert(b2.a === 2)
```

**Comment by natefaubion** [comment]
You also have to make sure that all partially applied constructors are bound too.

**Comment by natefaubion** [comment]
@michaelficarra In the specific case, that might work, but what about if you were sub-classing? You couldn't do:

``` js
function Parent() {
  if (!(this instanceof Parent) || Object.getOwnPropertyNames(this).length) {
    return new Parent();
  }
}
function Child() {
  this.foo = 42;
  Parent.call(this);
}
extends(Child, Parent);
```

Looks like binding is the way to go. I don't notice any downsides except a layer of indirection with the bound function, though I don't know if it works in the general case.

**Comment by LiamGoodacre** [comment]
Can anyone think of any further test cases?
