### ISSUE TITLE
adt.only checks are incorrect

### ISSUE THREAD

**Issue by gregwebs** [natefaubion/adt.js#8]
underscore.js and other js projects they use Object.prototype.toString.call to determine the type. The current checking does not work for strings for example.

Maybe it is best to leave adt.js out of this business, but show how to combine it with underscore/lodash ?

**Comment by gregwebs** [comment]
``` coffee
  only = (types...) ->
    checks = for type in types
      switch type
        when String then _.isString
        when null then _.isNull
        when undefined then _.isUndefined
    (x) ->
      return x if _(checks).any((check) -> check(x))
      throw new Error("unexpected type")
```

**Comment by natefaubion** [comment]
Can you give me a specific example that fails? There is special case code for String, Number, and Boolean to perform `typeof` checks since `instanceof` checks fails on literals. Maybe its a browser thing (though it shouldn't be)?

https://github.com/natefaubion/adt.js/blob/master/adt.js#L463
https://github.com/natefaubion/adt.js/blob/master/test/core.js#L204

**Comment by gregwebs** [comment]
yes, it is different in every browser: if you want to make this a server-side only function you can write test-cases and make this work, but client-side it will only work if you copy all the other client-side libraries. In Chrome adt.only(String) fails for me.

**Comment by natefaubion** [comment]
I'll work on setting up browser based tests. But I ran this brief snippet in Chrome, Safari, Firefox, IE9, and IE8 and they all checked out ok. Are you using the latest?

``` html
<!DOCTYPE HTML>
<script src="./adt.js"></script>
<script>
  var fn = adt.only(String);
  console.log(fn("asd") === "asd");
  console.log(fn("") === "");
  // Throws
  fn(null);
</script>
```

**Comment by gregwebs** [comment]
Your time would be much better spent making adt.js better than re-doing what has been done in many other client-side js libraries :)

You should just rip out the type-checking code from underscore.js (which is battle tested) and use that. Ideally it would be optional so that when I use underscore I don't have duplicate code.

**Comment by natefaubion** [comment]
I don't disagree with you about using toString comparisons, I just want to know what you are doing that makes it fail since I can't reproduce it in anyway. When you say it fails, how do you mean? Does it throw an error when it shouldn't or does it let values through that should throw an error. I need some code that I can test with.

**Comment by gregwebs** [comment]
```
var a = "abc"; a instanceof Function
false
```

We don't need any code to test if we just use time-tested code.

**Comment by natefaubion** [comment]
I don't follow your example at all or what it has to do with adt.only. I do need some code to test so I know that I can be confident that whatever solution put in has indeed fixed whatever bug there is.

if you pass in `adt.only("abc")` it will check whether passed in values match "abc" not just if its string.

``` js
var fn = adt.only("abc");

// OK
fn("abc");

// Error
fn("123");

```
